import os   #Versao 2
funcionarios = {
  '123' : ["Juninho Forró", "67 99996767", "juninho@forrozeiro123.com", "Garçom", "6767.67"],
  '898' : ["Severina Guerra", "19 99093939", "severina@guerradecanudos.com", "Atendente", "1896"],
  '656' : ["Chico Petisco", "89 40028922", "chico@petisco.com", "Cozinheiro", "2026"],
  '456' : ["Neymar Jr.", "83 201120215", "Neymar@Junio.com", "Pizzaiolo", "1621"]
}
menu_prin = ""
while menu_prin != "0":
  os.system('cls')
  print("|' ' ' ' ' ' ' ' ' ' ' ' ' ' '|")     #Primeira versão do layout, tentei fazer uma caixa de pizza kk
  print("|:                           :|")     # OBS: Alterar os "Resps" para um identificador melhor 
  print("|:::::::::::::::::::::::::::::|")
  print("|:::::::::::::::::::::::::::::|")
  print("|:::::-------------------:::::|")
  print("|::::/                   \\::::|")
  print("|:::|   Projeto PyPizza   |:::|")
  print("|::::\\                   /::::|")
  print("|::::::-----------------::::::|")
  print("|:::::::::::::::::::::::::::::|")
  print("|:::::::::::::::::::::::::::::|")
  print("|:                           :|")
  print("|. . . . . . . . . . . . . . .|")
  print()
  print("|:::::::::::::::::::::::::::::|")
  print("|:::   1 - Funcionários    :::|")
  print("|:::   2 - Cardápio        :::|")
  print("|:::   3 - Estoque         :::|")
  print("|:::   4 - Relátorio       :::|")
  print("|:::   5 - Informações     :::|")
  print("|:::   0 - Sair            :::|")
  print("|:::::::::::::::::::::::::::::|")
  menu_prin = input("|:::   Escolha uma opção: ")

  if menu_prin == '1':
    print()
    print("|:::::::::::::::::::::::::::::|")
    print("|:::      FUNCIONÁRIOS     :::|")
    print("|:::::::::::::::::::::::::::::|")
    print("|:::   1 - Cadastrar       :::|")
    print("|:::   2 - Pesquisar       :::|")
    print("|:::   3 - Alterar         :::|")
    print("|:::   4 - Excluir         :::|")
    print("|:::   0 - Menu Principal  :::|")
    print("|:::::::::::::::::::::::::::::|")
    menu_fun = input("|:::   Escolha uma opção: ")
    print()
    if menu_fun == '1':
      os.system('cls')
      print("|:::::::::::::::::::::::::::::|")
      print("|:::   Cadastrar novo      :::|")
      print("|:::     Funcionário       :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()

      nome = input("|:::  Nome: ")
      fone = input("|:::  Telefone: ")
      email = input("|:::  Email: ")
      cargo = input("|:::  Cargo: ")
      sala = input("|:::  Salário: ")
      id_funcionario = input("|:::  Id: ")
      print()
      print("Funcionário cadastrado!!")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print()

    elif menu_fun == '2':
      os.system('cls')
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|:::       Pesquisar       :::|")
      print("|:::      Funcionário      :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      id_funcionario = input("|:::   Informe o ID que deseja pesquisar: ")
      print()
      print("|:::   ID: ", id_funcionario)
      print("|:::   Nome: ")
      print("|:::   Telefone: ")
      print("|:::   Email: ")
      print("|:::   Cargo: ")
      print("|:::   Salário: ")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print()

    elif menu_fun == '3':
      os.system('cls')
      print("|:::::::::::::::::::::::::::::|")
      print("|:::     Alterar dados     :::|")
      print("|:::    do Funcionário     :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      id_funcionario = input("|:::   Id: ")
      print()
      nome = input("|:::  Nome: ")
      fone = input("|:::  Telefone: ")
      email = input("|:::  Email: ")
      idade = input("|:::  Idade: ")
      cargo = input("|:::  Cargo: ")
      sala = input("|:::   Salário: ")
      print ()
      print("|:::   Dados alterados com sucesso !! ")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
    elif menu_fun == '4':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::        Excluir        :::|")
      print("|:::      Funcionário      :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      id_funcionario = input("|:::   Informe o ID do funcionário que deseja excluir: ")
      print()
      print("Funcionário excluído com sucesso !! ")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_fun == '0':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Voltando ao      :::|")
      print("|:::    Menu Principal...  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
    else:
      print("|:::::::::::::::::::::::::::::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|:::     Volte Ao Menu     :::|")
      print("|:::   Principal e Tente   :::|")
      print("|:::      Novamente!!      :::|")
      print("|:::::::::::::::::::::::::::::|")
    print()
    input("Pressione 'ENTER' para continuar")

  elif menu_prin == '2':
    print()
    print("|:::::::::::::::::::::::::::::|")
    print("|:::        CARDÁPIO       :::|")
    print("|:::::::::::::::::::::::::::::|")
    print("|:::   1 - Pizzas          :::|")
    print("|:::   2 - Lanches         :::|")
    print("|:::   3 - Sobremesas      :::|")
    print("|:::   4 - Bebidas         :::|")
    print("|:::   0 - Menu Principal  :::|")
    print("|:::::::::::::::::::::::::::::|")
    menu_card = input("|:::   Escolha uma opção: ")
    print ()
    if menu_card == '1':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Menu Pizzas      :::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|:::   1 - Lista Pizzas    :::|")
      print("|:::   2 - Buscar Pizza    :::|")
      print("|:::   3 - Adicionar Pizza :::|")
      print("|:::   4 - Alterar Pizza   :::|")
      print("|:::   5 - Excluir Pizza   :::|")
      print("|:::   0 - Menu Principal  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      resp3 = input("|:::   Escolha uma opção: ")
      if resp3 == '1':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      elif resp3 == '2':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      elif resp3 == '3':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      elif resp3 == '4':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      elif resp3 == '5':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '0':
        print("|:::::::::::::::::::::::::::::|")
        print("|:::      Voltando ao      :::|")
        print("|:::    Menu Principal...  :::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      else:
        print("|:::::::::::::::::::::::::::::|")
        print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
        print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
        print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
        print("|:::::::::::::::::::::::::::::|")
        print("|:::     Volte Ao Menu     :::|")
        print("|:::   Principal e Tente   :::|")
        print("|:::      Novamente!!      :::|")
        print("|:::::::::::::::::::::::::::::|")
    elif menu_card == '2':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Menu Lanches     :::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|:::   1 - Lista Lanches   :::|")
      print("|:::   2 - Buscar Lanche   :::|")
      print("|:::   3 - AdicionarLanche :::|")
      print("|:::   4 - Alterar Lanche  :::|")
      print("|:::   5 - Excluir Lanche  :::|")
      print("|:::   0 - Menu Principal  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      resp3 = input("|:::   Escolha uma opção: ")
      if resp3 == '1':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '2':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '3':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '4':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '5':
        print("|:::::::::::::::::::::::::::::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::     ! ! AVISO ! !     :::|")
        print("|::::     ! ! ! ! ! !     ::::|")
        print("|:::::::::::::::::::::::::::::|")
        print("|::::                     ::::|")
        print("|:::    FUNÇÃO AINDA EM    :::|")
        print("|:::    DESENVOLVIMENTO    :::|")
        print("|::::                     ::::|")
        print("|:::::::::::::::::::::::::::::|")
      elif resp3 == '0':
        print("|:::::::::::::::::::::::::::::|")
        print("|:::      Voltando ao      :::|")
        print("|:::    Menu Principal...  :::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
      else:
        print("|:::::::::::::::::::::::::::::|")
        print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
        print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
        print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
        print("|:::::::::::::::::::::::::::::|")
        print()
        print("|:::::::::::::::::::::::::::::|")
        print("|:::     Volte Ao Menu     :::|")
        print("|:::   Principal e Tente   :::|")
        print("|:::      Novamente!!      :::|")
        print("|:::::::::::::::::::::::::::::|")
    elif menu_card == '3':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::     Menu Sobremesa    :::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_card == '4':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Menu Bebidas     :::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_card == '0':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Voltando ao      :::|")
      print("|:::    Menu Principal...  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
    else:
      print("|:::::::::::::::::::::::::::::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|:::     Volte Ao Menu     :::|")
      print("|:::   Principal e Tente   :::|")
      print("|:::      Novamente!!      :::|")
      print("|:::::::::::::::::::::::::::::|")
    print()
    input("Pressione 'ENTER' para continuar")
  elif menu_prin == '3':
    print()
    print("|:::::::::::::::::::::::::::::|")
    print("|:::        ESTOQUE        :::|")
    print("|:::::::::::::::::::::::::::::|") ########## Em Produção...
    print("|:::   1 - Lista Estoque   :::|")
    print("|:::   2 - Buscar Item     :::|")
    print("|:::   3 - Adicionar Item  :::|")
    print("|:::   4 - Remover Item    :::|")
    print("|:::   5 - Atualizar Item  :::|")
    print("|:::   0 - Menu Principal  :::|")
    print("|:::::::::::::::::::::::::::::|")
    menu_estq = input("|:::   Escolha uma opção: ")
    print()
    if menu_estq == '1':
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_estq == '2':
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_estq == '3':
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_estq == '4':
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_estq == '5':
      print("|:::::::::::::::::::::::::::::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::     ! ! AVISO ! !     :::|")
      print("|::::     ! ! ! ! ! !     ::::|")
      print("|:::::::::::::::::::::::::::::|")
      print("|::::                     ::::|")
      print("|:::    FUNÇÃO AINDA EM    :::|")
      print("|:::    DESENVOLVIMENTO    :::|")
      print("|::::                     ::::|")
      print("|:::::::::::::::::::::::::::::|")
    elif menu_estq == '0':
      print("|:::::::::::::::::::::::::::::|")
      print("|:::      Voltando ao      :::|")
      print("|:::    Menu Principal...  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
    else:
      print("|:::::::::::::::::::::::::::::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
      print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
      print("|:::::::::::::::::::::::::::::|")
      print()
      print("|:::::::::::::::::::::::::::::|")
      print("|:::     Volte Ao Menu     :::|")
      print("|:::   Principal e Tente   :::|")
      print("|:::      Novamente!!      :::|")
      print("|:::::::::::::::::::::::::::::|")
    print()
    input("Pressione 'ENTER' para continuar")
  elif menu_prin == '4':
    print()
    print("|:::::::::::::::::::::::::::::::::::::::::::::|")
    print("|:::               RELATORIOS              :::|")
    print("|:::::::::::::::::::::::::::::::::::::::::::::|")
    print("|:::    1 - Lista Geral De Funcionários    :::|")
    print("|:::    2 - Lista Geral Do Cardápio        :::|")
    print("|:::    3 - Lista Geral Do Estoque         :::|")
    print("|:::    4 - Lista de Funcioários por Cargo :::|")
    print("|:::    5 - Menu Principal                 :::|") 
    print("|:::::::::::::::::::::::::::::::::::::::::::::|")
    menu_rlt = input("|:::   Escolha uma opção: ")
    print()
    input("Pressione 'ENTER' para continuar")
  elif menu_prin == '5':
    print()
    print("|::::::::::::::::::::::::::::::::::::::::::|")
    print("|:::             INFORMAÇÕES            :::|")
    print("|::::::::::::::::::::::::::::::::::::::::::|")
    print("|::: Sistema De Gestão Para Pizzaria    :::|")
    print("|::: Desenvolvedor:                     :::|")
    print("|::: Isaias Vidal Medeiros              :::|")
    print("|::: Licença Pública MIT                :::|")
    print("|::: https://opensource.org/license/mit :::|")
    print("|::::::::::::::::::::::::::::::::::::::::::|")
    print()
    input("Pressione 'ENTER' para continuar")
  elif menu_prin == '0':
    print("|:::::::::::::::::::::::::::::|")
    print("|:::      Encerrando       :::|")
    print("|:::     O Programa em     :::|")
    print("|:::      3...2...1...     :::|")
    print("|:::::::::::::::::::::::::::::|")
    print()
  else:
    print("|:::::::::::::::::::::::::::::|")
    print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
    print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
    print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
    print("|:::::::::::::::::::::::::::::|")
    print()
    print("|:::::::::::::::::::::::::::::|")
    print("|:::     Volte Ao Menu     :::|")
    print("|:::   Principal e Tente   :::|")
    print("|:::      Novamente!!      :::|")
    print("|:::::::::::::::::::::::::::::|")
    print()
    input("Pressione 'ENTER' para continuar")

print("|:::::::::::::::::::::::::::::|")
print("|:::   Obrigado Por Usar   :::|")
print("|:::    O Programa!! :)    :::|")
print("|:::::::::::::::::::::::::::::|")
print()
print("|:::::::::::::::::::::::::::::|")
print("|:::     Até Mais !!  ;)   :::|")
print("|:::::::::::::::::::::::::::::|")
print("Fim do Programa!!!")


