def menu():
    print("|:::::::::::::::::::::::::::::|")
    print("|:::      Voltando ao      :::|")
    print("|:::    Menu Principal...  :::|")
    print("|:::::::::::::::::::::::::::::|")
    print()
def invalida():
    print("|:::::::::::::::::::::::::::::|")
    print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
    print("|:::  !  OPÇÃO INVÁLIDA !  :::|")
    print("|:::  ! ! ! ! ! ! ! ! ! !  :::|")
    print("|:::::::::::::::::::::::::::::|")
    print()
    print("|:::::::::::::::::::::::::::::|")
    print("|:::     Volte Ao Menu     :::|")
    print("|:::  E Escolha Uma Opção  :::|")
    print("|:::        Válida!!!      :::|")
    print("|:::::::::::::::::::::::::::::|")